### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by KaHuier** [likianta/lk-logger#1]
Python 3.8.8
很抱歉再次出现该问题 
当我升级到最新版后 在lk_utils\filesniff.py:15 中还是出现错误 
我看你已经导入了这个  from __future__ import annotations 
我以为是我代码问题尝试只进行导入 from lk_utils import filesniff 无意外 还是出现错误
我尝试把该处代码直接复制出来 直接运行 也就是
Path = DirPath = FilePath = str
Paths = DirPaths = FilePaths = list[Path]
不出意外 还是报错 我又尝试把list修改为List 就没问题了
同时我尝试了 
from __future__ import annotations
Paths:list[str] 
是可以的
我想是你这个写法是不兼容的 也就是 Paths = DirPaths = FilePaths = list[Path] 不被兼容

**Comment by KaHuier** [comment]
双下划线被转义了

**Comment by likianta** [comment]
这是我的一些工作疏漏导致的. 😅 我在该项目和其他项目中也找到了类似的问题.

我平时是在 Python 3.10 上工作. 在发布之前由人工检查代码向下的兼容性, 因此可能产生此类问题.

近期我会改用一些自动化工具 (比如 [这个](https://github.com/likianta/python-code-compat-checker)) 替代人工检查, 来扫描我的项目代码. 预计在最近两天将有修复后的 lk-logger, lk-utils 版本发布到 PyPI, 请关注一下后续的更新.

**Comment by likianta** [comment]
最新的版本 [5.3.0](https://pypi.org/project/lk-logger/) 已修复.
